# Generated by Django 5.1.6 on 2025-02-24 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email User')),
                ('password', models.CharField(max_length=50, verbose_name='User Password')),
                ('fullName', models.CharField(max_length=150, null=True, verbose_name='User Name')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='User Age')),
                ('contactNumber', models.CharField(max_length=10, null=True, verbose_name='User Contact Number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='userSora', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='userSoraSet', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
