# Generated by Django 5.1.6 on 2025-02-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSora', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=255, unique=True, verbose_name='User Name'),
        ),
    ]
