# Generated by Django 5.1.6 on 2025-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSora', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='User'),
        ),
    ]
