# Generated by Django 5.1.6 on 2025-04-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSora', '0008_ageuser_tb_educationleveluser_tb_rangesalary_tb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manyKid',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Many Kids'),
        ),
    ]
