# Generated by Django 5.1.6 on 2025-03-20 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeActions_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleAlternative', models.CharField(max_length=250, verbose_name='Alternative Name')),
                ('descriptionAlternative', models.TextField(verbose_name='Description Alternative')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAlternative_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkAlternative', models.TextField(verbose_name='Link Spotify Alternative')),
                ('alternativeAction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlternativeSora.alternativeactions_tb')),
            ],
        ),
    ]
