# Generated by Django 5.1.6 on 2025-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlternativeSora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaalternative_tb',
            name='authorAlternative',
            field=models.CharField(default='', max_length=250, verbose_name='Author Alternative'),
        ),
        migrations.AddField(
            model_name='mediaalternative_tb',
            name='nameAlternative',
            field=models.CharField(default='', max_length=250, verbose_name='Name Alternative'),
        ),
        migrations.AlterField(
            model_name='mediaalternative_tb',
            name='linkAlternative',
            field=models.TextField(verbose_name='Link Alternative'),
        ),
    ]
