# Generated by Django 5.1.6 on 2025-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlternativeSora', '0002_mediaalternative_tb_authoralternative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaalternative_tb',
            name='nameAlternative',
            field=models.CharField(max_length=250, verbose_name='Name Alternative'),
        ),
    ]
