# Generated by Django 5.1.6 on 2025-05-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlternativeSora', '0004_alter_mediaalternative_tb_authoralternative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaalternative_tb',
            name='authorAlternative',
        ),
    ]
