# Generated by Django 5.1.6 on 2025-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryTestimonie_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTest', models.CharField(max_length=100, verbose_name='Category Testimonies')),
            ],
        ),
        migrations.CreateModel(
            name='testimonies_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorTest', models.CharField(max_length=150, verbose_name='Author Testimonie')),
                ('descriptionTest', models.TextField(verbose_name='Description Testimonie')),
                ('videoTest', models.FileField(upload_to='media', verbose_name='Video Test')),
                ('articleTest', models.TextField(verbose_name='Article Test')),
            ],
        ),
    ]
