# Generated by Django 5.0.4 on 2025-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestimoniesSora', '0002_testimonies_tb_cattest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonies_tb',
            name='videoTest',
            field=models.TextField(verbose_name='Video Test'),
        ),
    ]
