# Generated by Django 5.1.6 on 2025-05-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsSora', '0003_usercontactconfidence_tb_namecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactconfidence_tb',
            name='nameContact',
            field=models.CharField(max_length=250, verbose_name='Name Contact'),
        ),
    ]
