# Generated by Django 5.1.6 on 2025-05-26 21:14

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsSora', '0004_alter_usercontactconfidence_tb_namecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attentionroute_tb',
            name='locationAR',
        ),
        migrations.RemoveField(
            model_name='attentionroute_tb',
            name='phoneAR',
        ),
        migrations.RemoveField(
            model_name='attentionroute_tb',
            name='whatsappAR',
        ),
        migrations.RemoveField(
            model_name='categoryar_tb',
            name='titleCat',
        ),
        migrations.AddField(
            model_name='categoryar_tb',
            name='descriptionCat',
            field=models.TextField(default='', verbose_name='Description Cat'),
        ),
        migrations.AddField(
            model_name='categoryar_tb',
            name='imageCat',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='media', verbose_name='Image Cat'),
        ),
        migrations.AddField(
            model_name='categoryar_tb',
            name='nameCat',
            field=models.CharField(default='', max_length=150, verbose_name='Title Cat'),
        ),
    ]
