# Generated by Django 5.1.6 on 2025-05-26 21:14

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsSora', '0005_remove_attentionroute_tb_locationar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryar_tb',
            name='descriptionCat',
            field=models.TextField(verbose_name='Description Cat'),
        ),
        migrations.AlterField(
            model_name='categoryar_tb',
            name='imageCat',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='media', verbose_name='Image Cat'),
        ),
        migrations.AlterField(
            model_name='categoryar_tb',
            name='nameCat',
            field=models.CharField(max_length=150, verbose_name='Title Cat'),
        ),
    ]
