# Generated by Django 5.1.6 on 2025-05-27 00:18

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsSora', '0007_rename_titlecat_attentionroute_tb_namecat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentionroute_tb',
            name='descriptionAttention',
            field=models.TextField(verbose_name='Description Attention'),
        ),
        migrations.AlterField(
            model_name='attentionroute_tb',
            name='imageAttention',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='media', verbose_name='Image Attention'),
        ),
        migrations.AlterField(
            model_name='attentionroute_tb',
            name='nameAttention',
            field=models.CharField(max_length=255, verbose_name='Name Attention'),
        ),
    ]
