# Generated by Django 5.1.6 on 2025-03-06 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleNote', models.CharField(max_length=100, verbose_name='Title Note')),
                ('contentNote', models.TextField(max_length=500, verbose_name='Content Note')),
                ('createdNote', models.DateTimeField(auto_now_add=True, verbose_name='Date Note')),
                ('isFavorite', models.BooleanField(default=False, verbose_name='Favorite Note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
