# Generated by Django 5.1.6 on 2025-03-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='podcastMedia_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkPodcast', models.TextField(verbose_name='Link Podcast')),
            ],
        ),
    ]
