# Generated by Django 5.1.6 on 2025-03-27 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleExam', models.CharField(max_length=250, verbose_name='Exam Name')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameQuestion', models.TextField(verbose_name='Question Name')),
                ('scoreQuestion', models.IntegerField(verbose_name='Question Score')),
                ('examBelong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamSorora.exam_tb')),
            ],
        ),
    ]
