# Generated by Django 5.1.6 on 2025-04-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamSorora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreExam_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minScore', models.IntegerField(verbose_name='Min Score')),
                ('maxScore', models.IntegerField(verbose_name='Max Score')),
                ('violenceType', models.CharField(blank=True, max_length=250, verbose_name='Violence Type')),
                ('messageScore', models.TextField(verbose_name='Message Score')),
                ('idExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamSorora.exam_tb', verbose_name='Exam')),
            ],
        ),
    ]
