# Generated by Django 5.0.4 on 2025-04-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamSorora', '0002_scoreexam_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionScore_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkAction', models.CharField(max_length=255, verbose_name='Link Action')),
                ('nameAction', models.CharField(max_length=255, verbose_name='Link Action')),
                ('idScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamSorora.scoreexam_tb')),
            ],
        ),
    ]
