# Generated by Django 5.1.6 on 2025-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipsSora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='nameTip',
            field=models.CharField(default=0, max_length=150, verbose_name='Tip Name'),
        ),
    ]
