# Generated by Django 5.1.6 on 2025-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipsSora', '0003_tips_badsituation_tips_descriptiontip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='badSituation',
            field=models.TextField(verbose_name='Bad Situation'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='descriptionTip',
            field=models.TextField(verbose_name='Description Field'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='goodSituation',
            field=models.TextField(verbose_name='Good Situation'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='nameTip',
            field=models.CharField(max_length=150, verbose_name='Tip Name'),
        ),
    ]
