# Generated by Django 5.1.6 on 2025-04-08 16:22

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TipsSora', '0004_alter_tips_badsituation_alter_tips_descriptiontip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='imageTip',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='media', verbose_name='Image Tip'),
        ),
    ]
